"""phase 5: add tool_calls and tool_call_id to messages

Revision ID: e6bafd0b7929
Revises: 53becaf98784
Create Date: 2026-05-10 03:59:26.051595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bafd0b7929'
down_revision: Union[str, Sequence[str], None] = '53becaf98784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_calls', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tool_call_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('tool_call_id')
        batch_op.drop_column('tool_calls')

    # ### end Alembic commands ###
